GET http://localhost:3000/config/

###

GET http://localhost:3000/config/Egg

###

//Do not add ',' at the end
POST http://localhost:3000/config
Content-Type: application/json

{
    "username": "AtharvMoment",
    "password": "$Egg21@vsianAI",
    "email": "atharvhasALIFE@gmail.com",
    "VIP": false,
    "created_date": 0,
    "updated_date": 0
}

###

DELETE http://localhost:3000/config/dorritoShah/