GET http://localhost:3000/config/

###

GET http://localhost:3000/config/Egg

###
GET http://localhost:3000/config/gF-2S46fBcwaSGds_sWtG6F2sZt52

###

//Do not add ',' at the end
POST http://localhost:3000/config
Content-Type: application/json

{
    "username": "OI41092",
    "password": "$Egg21@vsianAI",
    "email": "atharvhasALIFE@gmail.com",
    "VIP": false,
    "sessionId": "gF-2S46fBcwaSGds_sWtG6F2sZt52",
    "created_date": 0,
    "updated_date": 0,
    "resources": [
        {
            "id": 1,
            "amount": 6
        }
    ]
}

###

DELETE http://localhost:3000/config/OI41092/